package com.example.campushub.enums;

public enum Neo4jEventType {
    USER_PROFILE_UPDATED,
    USER_STATUS_CHANGED,
    USER_FOLLOWED,
    USER_UNFOLLOWED,
    POST_CREATED,
    POST_SHARED,
    POST_STATUS_CHANGED,
    POST_REACTION_CHANGED,
    POST_COMMENT_CHANGED,
    GROUP_CREATED,
    GROUP_MEMBER_APPROVED,
    GROUP_MEMBER_REMOVED,
    GROUP_DELETED,
    GROUP_NAME_UPDATED
}
